### PR TITLE
Removing routes from debugbar

### PR DESCRIPTION
**Pull request by NeptuneDesign**
**Hello here is the new version for routes filtering**

26973187-7ffb4d64-4d15-11e7-8bed-16915a3860e5
Removing routes from debugbar

### CODE REVIEW

**Comment by ghost** [comment]
why is it still not merged

**Comment by dv336699** [comment]
Same here. @garygreen would be possible to merge this?
Cheers

**Comment by NeptuneDesign** [comment]
Hello I realized a fork that includes masking the url with a regular expression (debugbar)
[https://github.com/NeptuneDesign/list-routes](https://github.com/NeptuneDesign/list-routes)

**Comment by Braunson** [comment]
@garygreen Any reason we can't merge this in?

**Pull request merged**
