### PR TITLE
Optimize code

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by garygreen** [comment]
This may seem like an improvement but I'm not so sure because you've just moved the presentation logic into the controller - that seems a bit strange to me. Even though registering variables in the view isn't ideal, it's directly related to the display and presentation logic so it's currently already in a logical place.

**Comment by andrey-helldar** [comment]
In my opinion, in an ideal to take out these variables in a configuration file from where and load through the services loaded by the controller. But this, given the specifics of the package, will be redundant. Therefore, I simplified the logic a bit, removing the definition of the variable from the view.
In any case, will not it be better to use the variables of the templateer `@php ... @endphp`? In my opinion, it will be more correct.

**Comment by garygreen** [comment]
Take example in the future if the package ended up doing:

```
<span class="label label-{{ $method }}">{{ $method }}</span>
```

Then defined each `.label-get`, `.label-delete` etc in the stylesheet. Suddenly you have to change your controller and config options to suite. Presentation logic doesn't belong in the controller. `@php` "more correct" in a php file? Meh. I don't see the point 😄

**Comment by andrey-helldar** [comment]
Hmm... You're right!

**Pull request closed without merging**
